title: 个人知识库
description: 内容聚合型知识博客
theme: stellar
url: https://xaoxuu.github.io/hexo-theme-stellar-examples/knowledge
root: /hexo-theme-stellar-examples/knowledge/
permalink: posts/:title/

index_generator:
  path: ''
  per_page: 3
  order_by: -date

archive_dir: archives
category_dir: categories
tag_dir: tags
archive_generator:
  enabled: true
  per_page: 10
  yearly: true
  monthly: false
  daily: false
category_generator:
  per_page: 10
tag_generator:
  per_page: 10
